# Generated by Django 5.0.3 on 2024-08-17 15:08

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("MP", "Mercado Pago"), ("SP", "Stripe")],
                        default="MP",
                        max_length=2,
                        verbose_name="provider",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(help_text="When we received the message"),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="payload",
                    ),
                ),
            ],
            options={
                "verbose_name": "webhook message",
                "verbose_name_plural": "webhook messages",
                "indexes": [
                    models.Index(
                        fields=["received_at"], name="payments_we_receive_084e69_idx"
                    )
                ],
            },
        ),
    ]
