# Generated by Django 4.1.3 on 2022-12-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Brief description for your profile. URLs are hyperlinked.",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="We are big on real names around here, so people know who is who.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="personal_website",
            field=models.URLField(
                blank=True, help_text="Your home page, blog or company site."
            ),
        ),
    ]
