TERMINALS = [
    "Adolfo Gonzales Chaves",
    "Almafuerte",
    "Alta Gracia",
    "Alvear",
    "Alejo Ledesma acc",
    "Anatuya",
    "Apostoles",
    "Arias",
    "Arrecifes - Bs As",
    "Ayacucho",
    "Azul",
    "Bahia Blanca",
    "Balcarce",
    "Bariloche",
    "Bella Vista",
    "Benito Juarez",
    "Berazategui",
    "Brandsen",
    "Buenos Aires",
    "Caleta Olivia",
    "Campana",
    "Canals Acc YPF ACA",
    "Capilla del Monte",
    "Cap Sarmiento - Bs As",
    "Castelli",
    "Catamarca",
    "Catriel",
    "Caucete",
    "Choele Choel",
    "Cinco Saltos",
    "Cipolletti",
    "Colon Bs As",
    "Comodoro Rivadavia",
    "Concordia",
    "Cordoba",
    "Coronel Pringles",
    "Corrientes",
    "Cosquin",
    "Cruz del Eje",
    "Cutral Co",
    "D. de Alvear (Pdor)",
    "Dean Funes",
    "Desaguadero (MZA)",
    "Dionisio Cerqueira",
    "Dolores",
    "Eldorado",
    "El Talar Terminal",
    "Embalse",
    "Escobar",
    "Esperanza",
    "Esquel",
    "Ezeiza",
    "Formosa",
    "General Alvear",
    "General Cabrera",
    "General Conesa",
    "General Pico",
    "General Roca",
    "Gobernador Virasoro",
    "Gualeguaychu",
    "Guamini",
    "Hughes YPF - SFE",
    "Jardin America",
    "Jesus Maria",
    "Jose C Paz",
    "Junin",
    "Justo Daract SLU",
    "Laboulaye CBA",
    "La Banda",
    "La Carlota",
    "La Falda",
    "La Lucila del Mar",
    "La Paz (MZA)",
    "La Plata",
    "La Rioja",
    "Lanus",
    "Laprida",
    "Las Flores",
    "Las Toninas",
    "Las Varillas",
    "Liniers",
    "Lujan",
    "Mar del Plata",
    "Mendoza",
    "Merlo",
    "Mina Clavero",
    "Miramar",
    "Moron",
    "Moreno Colectora Las Piedras",
    "Necochea",
    "Neuquen",
    "Parana",
    "Paso de los Libres",
    "Pergamino",
    "Pico Truncado",
    "Pigue",
    "Pilar BsAs",
    "Pinamar",
    "Plottier",
    "Posadas",
    "Puerto Iguazu",
    "Puerto Madryn",
    "Punta Alta",
    "Rafaela",
    "Ramos Mejia",
    "Realico",
    "Resistencia",
    "Rio Colorado",
    "Rio Cuarto",
    "Rio Gallegos",
    "Rosario",
    "Rufino",
    "Salta",
    "San A. de Areco GNC PUMA",
    "San Antonio Oeste",
    "San Clemente del Tuyu",
    "San Francisco",
    "San Juan",
    "San Luis",
    "San Martin (MZA)",
    "San Miguel de Tucuman",
    "San Miguel del Monte",
    "San Rafael",
    "Santa Fe",
    "Santa Rosa",
    "Santa Rosa de Calamuchita",
    "Santa Teresita",
    "Santiago del Estero",
    "Tandil",
    "Term Gral Levalle CBA",
    "Termas de Rio Hondo",
    "Terminal Sampacho",
    "Trelew",
    "Trenque Lauquen",
    "Tres Arroyos",
    "Vedia",
    "Venado Tuerto",
    "Vergara y Gaona Aveljhon-VTessei",
    "Vicuña Mackenna",
    "Viedma",
    "Villa Carlos Paz",
    "Villa de Las Rosas",
    "Villa de Maria",
    "Villa Dolores",
    "Villa General Belgrano",
    "Villa Gesell",
    "Villa Mercedes SLU",
    "Villa Regina",
    "Zapala",
]
