TERMINALS = [
    "Adolfo Gonzales Chaves",
    "Almafuerte",
    "Alta Gracia",
    "Alvear",
    "Anatuya",
    "Apostoles",
    "Arias",
    "Ayacucho",
    "Azul",
    "Bahia Blanca",
    "Balcarce",
    "Bariloche",
    "Bella Vista",
    "Benito Juarez",
    "Berazategui",
    "Brandsen",
    "Buenos Aires",
    "Caleta Olivia",
    "Campana",
    "Capilla del Monte",
    "Castelli",
    "Catamarca",
    "Catriel",
    "Caucete",
    "Choele Choel",
    "Cinco Saltos",
    "Cipolletti",
    "Comodoro Rivadavia",
    "Concordia",
    "Cordoba",
    "Coronel Pringles",
    "Corrientes",
    "Cosquin",
    "Cruz del Eje",
    "Cutral Co",
    "Dean Funes",
    "Dionisio Cerqueira",
    "Dolores",
    "Eldorado",
    "Embalse",
    "Escobar",
    "Esperanza",
    "Esquel",
    "Ezeiza",
    "Formosa",
    "General Alvear",
    "General Cabrera",
    "General Conesa",
    "General Pico",
    "General Roca",
    "Gobernador Virasoro",
    "Gualeguaychu",
    "Guamini",
    "Jardin America",
    "Jesus Maria",
    "Jose C Paz",
    "Junin",
    "La Banda",
    "La Carlota",
    "La Falda",
    "La Lucila del Mar",
    "La Plata",
    "La Rioja",
    "Lanus",
    "Laprida",
    "Las Flores",
    "Las Toninas",
    "Las Varillas",
    "Lujan",
    "Mar del Plata",
    "Mendoza",
    "Merlo",
    "Mina Clavero",
    "Miramar",
    "Moron",
    "Necochea",
    "Neuquen",
    "Parana",
    "Paso de los Libres",
    "Pergamino",
    "Pico Truncado",
    "Pigue",
    "Pinamar",
    "Plottier",
    "Posadas",
    "Puerto Iguazu",
    "Puerto Madryn",
    "Punta Alta",
    "Rafaela",
    "Ramos Mejia",
    "Realico",
    "Resistencia",
    "Rio Colorado",
    "Rio Cuarto",
    "Rio Gallegos",
    "Rosario",
    "Rufino",
    "Salta",
    "San Antonio Oeste",
    "San Clemente del Tuyu",
    "San Francisco",
    "San Juan",
    "San Luis",
    "San Miguel de Tucuman",
    "San Miguel del Monte",
    "San Rafael",
    "Santa Fe",
    "Santa Rosa",
    "Santa Rosa de Calamuchita",
    "Santa Teresita",
    "Santiago del Estero",
    "Tandil",
    "Termas de Rio Hondo",
    "Trelew",
    "Trenque Lauquen",
    "Tres Arroyos",
    "Venado Tuerto",
    "Viedma",
    "Villa Carlos Paz",
    "Villa de Las Rosas",
    "Villa de Maria",
    "Villa Dolores",
    "Villa General Belgrano",
    "Villa Gesell",
    "Villa Mercedes",
    "Villa Regina",
    "Zapala",
]
