TERMINALS = [
    "9 de Julio",
    "Abra Pampa",
    "Achiras",
    "Adolfo Gonzales Chaves",
    "Adrogué",
    "Agua de Oro",
    "Aguaray",
    "Aguas Blancas",
    "Aguas Verdes",
    "Aguilares",
    "Agustina",
    "Agustín",
    "Aimogasta",
    "Alba Posse",
    "Alberti",
    "Alcaraz",
    "Alcira Gigena",
    "Alcorta",
    "Aldea San Antonio",
    "Alejandro",
    "Alejandro Korn",
    "Alejandro Roca",
    "Alejo Ledesma",
    "Algarrobo",
    "Algarrobo del Águila",
    "Alicia",
    "Allen",
    "Almafuerte",
    "Alta Gracia",
    "Alto Pencoso",
    "Altos de Chipión",
    "Aluminé",
    "Alvear",
    "Amaicha del Valle",
    "America",
    "Andalgalá",
    "Andres De Giles",
    "Angastaco",
    "Angel Etcheverry",
    "Angélica",
    "Animaná",
    "Anisacate",
    "Antonio",
    "Antonio Oeste",
    "Antonio de Areco",
    "Antonio de Padua",
    "Antonio de la Paz",
    "Aparicio",
    "Apolinario Saravia",
    "Apóstoles",
    "Aranguren",
    "Arias",
    "Aristóbulo del Valle",
    "Armstrong",
    "Arrecifes",
    "Arribeños",
    "Arroyito",
    "Arroyo Cabral",
    "Arroyo Seco",
    "Arroyo Verde",
    "Arrufo",
    "Ascensión",
    "Ascochinga",
    "Ausonia",
    "Avellaneda",
    "Aviá Teraí",
    "Ayacucho",
    "Azul",
    "Azul Pampa",
    "Añatuya",
    "Añelo",
    "Bahía Blanca",
    "Baibiene",
    "Bajada Colorada",
    "Bajada del Agrio",
    "Bajo Caracoles",
    "Balcarce",
    "Balde",
    "Balnearia",
    "Bandera",
    "Banderalo",
    "Banfield",
    "Baradero",
    "Barda del Medio",
    "Barrancas",
    "Barranqueras",
    "Barreal",
    "Basail",
    "Basavilbaso",
    "Bañado de Ovanta",
    "Bell Ville",
    "Bella Vista",
    "Beltrán",
    "Belén",
    "Benito Juarez",
    "Berazategui",
    "Berazategui Oeste",
    "Berisso",
    "Bermejo",
    "Berna",
    "Bernal",
    "Bernardo",
    "Bernardo de Irigoyen",
    "Bernardo del Tuyú",
    "Bernasconi",
    "Berrotarán",
    "Bialet Massé",
    "Bolivar",
    "Bordenave",
    "Bovril",
    "Bowen",
    "Bragado",
    "Brandsen",
    "Brazo Largo",
    "Brinkmann",
    "Buena Esperanza",
    "Buena Vista",
    "Buenos Aires",
    "Burzaco",
    "Buta Ranquil",
    "Béccar",
    "Cachari",
    "Cafayate",
    "Caimancito",
    "Calchaqui",
    "Caleta Olivia",
    "Calingasta",
    "Campana",
    "Campo Grande",
    "Campo Largo",
    "Campo Viera",
    "Canals",
    "Cancha Carrera",
    "Candelaria",
    "Capilla Del Monte",
    "Capiovi",
    "Capitan Sarmiento",
    "Caraguatay",
    "Carcarañá",
    "Carhué",
    "Cariló",
    "Carlos",
    "Carlos Casares",
    "Carlos Centro",
    "Carlos Minas",
    "Carlos Pellegrini",
    "Carlos Tejedor",
    "Carlos de Bariloche",
    "Carmen de Areco",
    "Carmen de Patagones",
    "Carnerillo",
    "Carpintería",
    "Carreras",
    "Casa Grande",
    "Casa de Piedra",
    "Casalins",
    "Casbas",
    "Caseros",
    "Casilda",
    "Castelar",
    "Castelli",
    "Catamarca",
    "Catriel",
    "Catrilo",
    "Caucete",
    "Caviahue-Copahue",
    "Cayastá",
    "Caá Catí",
    "Cañada Rosquín",
    "Cañada de Gómez",
    "Cañada de Luque",
    "Cañadón Seco",
    "Cañuelas",
    "Ceibas",
    "Centenario",
    "Ceres",
    "Cerrillos",
    "Cerrito",
    "Cerro Azul",
    "Cerro Dragón",
    "Chabas",
    "Chacabuco",
    "Chajan",
    "Chajarí",
    "Chalicán",
    "Challaco",
    "Chamical",
    "Chapadmalal",
    "Charata",
    "Charbonier",
    "Charras",
    "Chascomús",
    "Chazón",
    "Chañar",
    "Chañar Viejo",
    "Chelforó",
    "Chepes",
    "Chichinales",
    "Chilecito",
    "Chillar",
    "Chimpay",
    "Chivilcoy",
    "Choele Choel",
    "Chos Malal",
    "Chumbicha",
    "Cinco Saltos",
    "Cipolletti",
    "Ciudad Perico",
    "Claromeco",
    "Claypole",
    "Clemente del Tuyu",
    "Clemente del Tuyú",
    "Clorinda",
    "Cobo",
    "Colonia Caroya",
    "Colonia Dora",
    "Colonia Santa Rosa",
    "Colón",
    "Comallo",
    "Comandante Luis Piedrabuena",
    "Comodoro Rivadavia",
    "Concarán",
    "Concepcion",
    "Concepcion Del Uruguay",
    "Concepción del Bermejo",
    "Concordia",
    "Confluencia",
    "Coronel Baigorria",
    "Coronel Belisle",
    "Coronel Dorrego",
    "Coronel Du Graty",
    "Coronel Granada",
    "Coronel Juan Solá",
    "Coronel Mollinedo",
    "Coronel Pringles",
    "Coronel Suarez",
    "Coronel Vidal",
    "Corral de Bustos",
    "Corrientes",
    "Cortaderas",
    "Corzuela",
    "Cosme",
    "Cosquín",
    "Costa Sacate",
    "Crespo",
    "Cristóbal",
    "Cruz Alta",
    "Cruz del Eje",
    "Cuesta Blanca",
    "Curuzú Cuatiá",
    "Cutral Có",
    "Cuyin Manzano",
    "Córdoba",
    "Daireaux",
    "Dalmacio Velez Sarsfield",
    "Darregueira",
    "Darwin",
    "Del Campillo",
    "Del Viso",
    "Desaguadero",
    "Despeñaderos",
    "Devoto",
    "Deán Funes",
    "Diamante",
    "Diego de Alvear",
    "Dina Huapi",
    "Dolavon",
    "Don Torcuato",
    "Dos de Mayo",
    "Dragones",
    "Duggan",
    "Eduardo Castex",
    "El Alcazar",
    "El Bolsón",
    "El Calafate",
    "El Carril",
    "El Chaltén",
    "El Colorado",
    "El Condor",
    "El Cuy",
    "El Espinillo",
    "El Foyel",
    "El Galpón",
    "El Hoyo",
    "El Manzano",
    "El Milagro",
    "El Mojón",
    "El Mollar",
    "El Nihuil",
    "El Pluma",
    "El Pueblito",
    "El Quebrachal",
    "El Retiro",
    "El Salitral",
    "El Salto",
    "El Soberbio",
    "El Sosneado",
    "El Talar de Pacheco",
    "El Trebol",
    "El Tío",
    "El Volcan",
    "Eldorado",
    "Elena",
    "Elortondo",
    "Embajador Martini",
    "Embalse",
    "Empedrado",
    "Ensenada",
    "Epuyén",
    "Escobar",
    "Esperanza",
    "Espin",
    "Esquel",
    "Esquina",
    "Estacas",
    "Estanislao del Campo",
    "Esteban",
    "Eugenio Bustos",
    "Ezeiza",
    "Ezpeleta",
    "Famaillá",
    "Federación",
    "Federal",
    "Feliciano",
    "Fernández",
    "Fiambalá",
    "Firmat",
    "Fitz Roy",
    "Florencia",
    "Florencio Varela",
    "Formosa",
    "Forres",
    "Fortuna",
    "Fortín Olavarría",
    "Fraga",
    "Fraile Pintado",
    "Francisco",
    "Francisco Madero",
    "Francisco Solano",
    "Francisco del Chañar",
    "Francisco del Monte de Oro",
    "Franck",
    "Frontera",
    "Frías",
    "Gaiman",
    "Gamay",
    "Gancedo",
    "Gaona",
    "Garayalde",
    "Garuhape",
    "Garupá",
    "Garza",
    "Garín",
    "Gato Colorado",
    "Genaro",
    "General Acha",
    "General Alvear",
    "General Arenales",
    "General Belgrano",
    "General Cabrera",
    "General Campos",
    "General Conesa",
    "General Deheza",
    "General Enrique Godoy",
    "General Enrique Mosconi",
    "General Fernández Oro",
    "General Galarza",
    "General Guemes",
    "General Guido",
    "General José de San Martín",
    "General Juan Madariaga",
    "General Lamadrid",
    "General Lavalle",
    "General Levalle",
    "General Mansilla",
    "General Pacheco",
    "General Pico",
    "General Pinedo",
    "General Pinto",
    "General Piran",
    "General Pizarro",
    "General Ramírez",
    "General Roca",
    "General San Martin",
    "General Villegas",
    "Gerónimo",
    "Gobernador Castro",
    "Gobernador Costa",
    "Gobernador Crespo",
    "Gobernador Gregores",
    "Gobernador Roca",
    "Gobernador Virasoro",
    "González Catán",
    "González Moreno",
    "Goya",
    "Gral Guemes",
    "Grand Bourg",
    "Gregoria Pérez de Denis",
    "Gregorio",
    "Gualeguay",
    "Gualeguaychú",
    "Guamini",
    "Guatraché",
    "Guer Aike",
    "Guerrero",
    "Guillermo",
    "Gálvez",
    "Haedo",
    "Hasenkamp",
    "Henderson",
    "Hermoso Campo",
    "Hernando",
    "Hernández",
    "Herrera",
    "Hinojo",
    "Hipólito Yrigoyen",
    "Huacalera",
    "Hualtaran",
    "Huanchillas",
    "Huerta Grande",
    "Hughes",
    "Huinca Renanco",
    "Humahuaca",
    "Humboldt",
    "Hurlingham",
    "Ibarreta",
    "Icaño",
    "Ignacio",
    "Ingeniero Juárez",
    "Ingeniero Luiggi",
    "Ingeniero Luis A. Huergo",
    "Ingeniero Miguel Sajaroff",
    "Inriville",
    "Intendente Alvear",
    "Iriarte",
    "Isidro",
    "Isla Verde",
    "Ita-ibate",
    "Itatí",
    "Iturbe",
    "Ituzaingo",
    "Ituzaingó",
    "Jacinto Arauz",
    "Jaime de la Frontera",
    "James Craik",
    "Jardin America",
    "Javier",
    "Javier Department",
    "Jesús María",
    "Joaquín V. González",
    "Jocoli",
    "Jorge",
    "Jose",
    "Jose de la Dormida",
    "José",
    "José C. Paz",
    "José de Las Salinas",
    "José de San Martín",
    "Jovita",
    "Juan",
    "Juan Bautista Alberdi",
    "Juan José Paso",
    "Jujuy",
    "Junín",
    "Junín de los Andes",
    "Justiniano Posse",
    "Justo",
    "Justo Daract",
    "Juárez Celman",
    "La Banda",
    "La Bolsa",
    "La Carlota",
    "La Clotilde",
    "La Cocha",
    "La Consulta",
    "La Criolla",
    "La Cruz",
    "La Cumbre",
    "La Dormida",
    "La Falda",
    "La Francia",
    "La Granja",
    "La Laguna",
    "La Leóna",
    "La Lucila del Mar",
    "La Matanza",
    "La Merced",
    "La Noria",
    "La Para",
    "La Paz",
    "La Plata",
    "La Playosa",
    "La Porteña",
    "La Quiaca",
    "La Reforma",
    "La Rincónada",
    "La Rioja",
    "La Serena",
    "La Toma",
    "Laborde",
    "Laboulaye",
    "Laferrere",
    "Lafinur",
    "Lago Hermoso",
    "Lago Puelo",
    "Laguna Blanca",
    "Laguna Larga",
    "Laguna Naick Neck",
    "Laguna Paiva",
    "Laguna Yema",
    "Lamarque",
    "Langueyú",
    "Lanus",
    "Laprida",
    "Larroque",
    "Larroude",
    "Las Armas",
    "Las Breñas",
    "Las Casuarinas",
    "Las Catitas",
    "Las Chapas",
    "Las Coloradas",
    "Las Cortaderas",
    "Las Cuevas",
    "Las Flores",
    "Las Garzas",
    "Las Grutas",
    "Las Heras",
    "Las Lajas",
    "Las Lajitas",
    "Las Leñas",
    "Las Lomitas",
    "Las Mojarras",
    "Las Parejas",
    "Las Peñas",
    "Las Plumas",
    "Las Rabonas",
    "Las Rosas",
    "Las Tapias",
    "Las Toninas",
    "Las Toscas",
    "Las Varas",
    "Las Varillas",
    "Las Vegas",
    "Las Vertientes",
    "Lavalle",
    "Le Marchand",
    "Leandro N. Alem",
    "Ledesma",
    "Leleque",
    "Lezama",
    "Libano",
    "Libertador General San Martín",
    "Lincoln",
    "Liniers",
    "Llambí Campbell",
    "Llavallol",
    "Lobería",
    "Lobos",
    "Lomas de Vallejos",
    "Lomas de Zamora",
    "Loncopué",
    "Londres",
    "Longchamps",
    "Lorenzo",
    "Loreto",
    "Los Altares",
    "Los Altos",
    "Los Antiguos",
    "Los Cardos",
    "Los Cocos",
    "Los Condores",
    "Los Frentones",
    "Los Hornillos",
    "Los Menucos",
    "Los Molles",
    "Los Penitentes",
    "Los Pirpintos",
    "Los Pozos",
    "Los Reartes",
    "Los Repollos",
    "Los Tamariscos",
    "Luca",
    "Lucas González",
    "Lucio V. Mansilla",
    "Lugones",
    "Luis",
    "Luis Beltran",
    "Luis Guillon",
    "Lujan",
    "Lujan De Cuyo",
    "Luján",
    "Lules",
    "Lumb",
    "Lumbreras",
    "Luque",
    "Macachín",
    "Machagai",
    "Maciá",
    "Magdalena",
    "Maggiolo",
    "Maimara",
    "Maipú",
    "Makallé",
    "Malabrigo",
    "Malargüe",
    "Malena",
    "Malvinas Argentinas",
    "Maquinchao",
    "Mar Chiquita",
    "Mar De Ajo",
    "Mar del Plata",
    "Mar del Sur",
    "Mar del Tuyú",
    "Marayes",
    "Marcelino Escalada",
    "Marcos",
    "Marcos Juárez",
    "Marcos Sierra",
    "Margarita",
    "Margarita Belén",
    "Martin de las Escobas",
    "Martín",
    "Martín de los Andes",
    "Martínez",
    "María Grande",
    "María Juana",
    "María Teresa",
    "Mayor Buratovich",
    "Mburucuyá",
    "Media Agua",
    "Melincué",
    "Melo",
    "Mendoza",
    "Mercedes",
    "Merlo",
    "Metan",
    "Micaela Cascallares",
    "Miguel",
    "Miguel Riglos",
    "Miguel de Tucumán",
    "Miguel del Monte",
    "Mina Clavero",
    "Ministro Ramos Mexía",
    "Miraflores",
    "Miramar",
    "Mocoreta",
    "Monasterio",
    "Mones Cazón",
    "Monte Buey",
    "Monte Caseros",
    "Monte Comán",
    "Monte Cristo",
    "Monte Grande",
    "Monte Hermoso",
    "Monte Maiz",
    "Monte Quemado",
    "Monte Redondo",
    "Monteagudo",
    "Montecarlo",
    "Monteros",
    "Moreno",
    "Morteros",
    "Morón",
    "Munro",
    "Murphy",
    "Médanos",
    "Naschel",
    "Navarro",
    "Necochea",
    "Nelson",
    "Neuquén",
    "Nicolas",
    "Nogoyá",
    "Nono",
    "Nonogasta",
    "Nueva Galia",
    "Nueve de Julio",
    "Nuevo Torino",
    "Obera",
    "Obispo Trejo",
    "Olavarría",
    "Oliva",
    "Olta",
    "Oncativo",
    "Oro Verde",
    "Orán",
    "Padre Buodo",
    "Palma Sola",
    "Palo Santo",
    "Palpalá",
    "Pampa de los Guanacos",
    "Pampa del Infierno",
    "Pampayasta",
    "Paraná",
    "Paranácito",
    "Pareditas",
    "Pascanas",
    "Paso Cardenal Antonia Samoré",
    "Paso de Indios",
    "Paso de la Patria",
    "Paso de los Libres",
    "Patquía",
    "Patricio del Chañar",
    "Pedro",
    "Pedro Luro",
    "Pedro de Jujuy",
    "Pehuajó",
    "Pellegrini",
    "Pergamino",
    "Perito Moreno",
    "Perú",
    "Pichanal",
    "Pico Truncado",
    "Picún Leufú",
    "Piedra del Águila",
    "Piedras Blancas",
    "Piedritas",
    "Pieres",
    "Pigue",
    "Pila",
    "Pilar",
    "Pilcaniyeu",
    "Pinamar",
    "Pino Hachado",
    "Pinto",
    "Piquillín",
    "Pirane",
    "Pirovano",
    "Plaza Huincul",
    "Plottier",
    "Pocito",
    "Pocitos",
    "Pomona",
    "Posadas",
    "Potrerillos",
    "Pourtale",
    "Pozo del Molle",
    "Pozo del Tigre",
    "Presidencia Roque Saenz Pena",
    "Presidencia de la Plaza",
    "Puan",
    "Pueblo Brugo",
    "Puelches",
    "Puente del Inca",
    "Puerto Deseado",
    "Puerto Esperanza",
    "Puerto Iguazú",
    "Puerto Leoni",
    "Puerto Libertad",
    "Puerto Madryn",
    "Puerto Manzano",
    "Puerto Piray",
    "Puerto Ramada",
    "Puerto Rico",
    "Puerto San Julián",
    "Puerto Santa Cruz",
    "Pumahuasi",
    "Punta Alta",
    "Punta de Vacas",
    "Punta del Medano",
    "Purmamarca",
    "Quebracho",
    "Quemu Quemu",
    "Quilino",
    "Quilmes",
    "Quilmes Oeste",
    "Quimilí",
    "Quines",
    "Quitilipi",
    "Rafael",
    "Rafael Castillo",
    "Rafael Obligado",
    "Rafaela",
    "Ramallo",
    "Ramos Mejía",
    "Ranchos",
    "Rauch",
    "Rawson",
    "Rayo Cortado",
    "Real del Padre",
    "Realico",
    "Reconquista",
    "Recreo",
    "Reduccion",
    "Resistencia",
    "Reta",
    "Rincon",
    "Rincón de Los Sauces",
    "Rio Ceballos",
    "Rio Grande",
    "Rio Primero",
    "Rio Villegas",
    "Rivera",
    "Robles",
    "Rodeo",
    "Rojas",
    "Roque",
    "Roque Pérez",
    "Rosario",
    "Rosario de la Frontera",
    "Rosario del Tala",
    "Rufino",
    "Río Colorado",
    "Río Cuarto",
    "Río Gallegos",
    "Río Mayo",
    "Río Segundo",
    "Río Tala",
    "Río Tercero",
    "Río Turbio",
    "Río de los Sauces",
    "Vicente",
    "Victor",
    "Vicuña Mackenna",
]
