# Generated by Django 4.1.7 on 2023-02-26 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(
                help_text="Please use upper case with discount value eg: SUMMER10",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
