# Generated by Django 4.1.7 on 2023-02-26 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_alter_coupon_active_alter_coupon_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(
                help_text="Please use capital letters without spaces. Ex: SUMMER10",
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z0-9]*$",
                        "Please use only uppercase letters and numbers without spaces.",
                    )
                ],
            ),
        ),
    ]
