# Generated by Django 4.1.7 on 2023-02-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0003_alter_coupon_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"ordering": ("-valid_to",)},
        ),
    ]
