# Generated by Django 4.2.2 on 2023-11-23 14:47

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0005_alter_coupon_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(
                help_text="Please use capital letters without spaces. Ex: SUMMER10",
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z0-9]*$",
                        "Please use only uppercase letters and numbers without spaces.",
                    )
                ],
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount",
            field=models.PositiveIntegerField(
                help_text="Percentage value (0 to 100%)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="discount",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="valid from"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(verbose_name="valid to"),
        ),
    ]
