# Generated by Django 5.0.3 on 2024-06-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0006_alter_coupon_active_alter_coupon_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={
                "ordering": ("valid_to",),
                "verbose_name": "coupon",
                "verbose_name_plural": "coupons",
            },
        ),
    ]
