COMPANIES = [
    "Via Tac",
    "KMB",
    "El Cometa",
    "Tolkeyen Patagonia",
    "Nordic Travel",
    "Autotransporte 21",
    "Autobuses Quirquincho",
    "R\u00e1pido Internacional",
    "Empresa Silvia",
    "Albizzatti",
    "Transportes Rinc\u00f3n",
    "Aerobols\u00f3n",
    "Alto Limay",
    "Expreso Singer",
    "JBL",
    "Expreso del Oeste",
    "Buses Potos\u00ed",
    "La Encarnacena",
    "Rio Uruguay",
    "La Uni\u00f3n",
    "V\u00eda Tac",
    "Central Argentino",
    "Lazo",
    "Socsa",
    "El Alba del Sur",
    "Eticket",
    "Sarmiento",
    "V\u00eda Bariloche",
    "Expreso Alberino",
    "Aguila Dorada Bis",
    "Taqsa",
    "Evelia",
    "C\u00f3ndor Estrella",
    "Rutamar",
    "Dumascat",
    "Aeroangostura",
    "Sierras Sur",
    "Balut",
    "Empresa Tas",
    "Aymar\u00e1 Turismo",
    "Macor",
    "Nuestra Se\u00f1ora de la Asunci\u00f3n - Argentina",
    "Chalt\u00e9n Travel",
    "Valle del Sol",
    "Colonia Express",
    "Rio Uruguay de Kruk Lila Maria",
    "El \u00c1guila",
    "Guaire\u00f1a",
    "Fredes Turismo",
    "San Juan Mar del Plata",
    "Crucero del Norte",
    "20 de Junio",
    "Platabus",
    "Empresa Vallecito",
    "\u00d1and\u00fa del Sur",
    "Sol Bus",
    "Reta Tur",
    "Micromar",
    "Puma Bus",
    "Ray Bus",
    "Horianski",
    "El Practico",
    "La Diligencia",
    "Transfer Line",
    "El Rosarino",
    "Rutatlantica",
    "Diferencial Transierras",
    "Buses Lep",
    "Transporte Serrano",
    "Union Platense",
    "El Triunfo",
    "Leader",
    "Nossar",
    "El Tat\u00fa Carretero",
    "Cal Tur",
    "El Turista",
    "Gray Line",
    "Tony Tur",
    "JoviBus",
    "Petrobus",
    "Cooperativa Sportman",
    "La Trochita",
    "El Pulqui",
    "ETAP",
    "Expreso R\u00edo Paran\u00e1",
    "Del Sur y Media Agua",
    "Empresa General Artigas",
    "La Yute\u00f1a",
    "Ersa",
    "La Paraguaya Internacional",
    "Gustavo Chavez Turismo",
    "Masterbus",
    "Bus Vitivin\u00edcola",
    "Transportes Automotores 20 de Junio S.A.",
    "Puerto Tirol",
    "Itati",
    "Crucero del Sur",
    "Cata Internacional",
    "El Valle",
    "Iselin",
    "25 de Agosto",
    "Transporte Las Grutas",
    "Tramat",
    "Ceferino",
    "Andesmar",
    "Sierras Cordobesas",
    "Expreso Paraguay",
    "Turismo Uspallata",
    "Royal Class",
    "Tren Patagonico",
    "Microsur",
    "Marga",
    "Fono Bus",
    "Transaustral",
    "Buttini",
    "Tienda Le\u00f3n",
    "Expreso Sauce",
    "Plusmar",
    "Expreso La Plata",
    "Capital del Monte",
    "Expreso Hernandarias",
    "R\u00e1pido Bus",
    "Eder",
    "La Santaniana",
    "Potos\u00ed Buses",
    "Tata R\u00e1pido",
    "Vosa",
    "Sierras de Calamuchita",
    "Betel Ejecutivo",
    "Transporte San Jose",
    "El Cometa Bis",
    "Intercordoba",
    "La Serranita",
    "Expreso Transamericano",
    "Rio Uruguay de Flecha de Oro",
    "Chevallier",
]

SEAT_CHART_TITLES = [
    "Cama",
    "Cama Executivo",
    "Cama Individual",
    "Cama Suite",
    "Semi Cama",
    "Semi Cama Promocional",
    "Semi Cama Promocional No Reembolsable",
]


SEMICAMA_PROMO = {
    "lower": {
        "enabledSeats": [],
        "labels": {
            "00": "?",
            "01": "?",
            "02": "?",
            "03": "?",
            "10": "?",
            "11": "?",
            "12": "?",
            "13": "?",
            "20": "?",
            "21": "?",
            "22": "?",
            "23": "?",
            "30": "60",
            "31": "61",
            "32": "?",
            "33": "?",
            "40": "62",
            "41": "63",
            "42": "?",
            "43": "73",
            "50": "64",
            "51": "65",
            "52": "?",
            "53": "75",
            "60": "66",
            "61": "67",
            "62": "?",
            "63": "77",
            "70": "?",
            "71": "?",
            "72": "?",
            "73": "?",
            "80": "?",
            "81": "?",
            "82": "?",
            "83": "?",
            "90": "?",
            "91": "?",
            "92": "?",
            "93": "?",
            "100": "?",
            "101": "?",
            "102": "?",
            "103": "?",
            "110": "?",
            "111": "?",
            "112": "?",
            "113": "?",
        },
        "options": {
            "map": {
                "rows": 11,
                "columns": 4,
                "seatTypes": {
                    "default": {
                        "label": "SemiCama",
                        "price": 20769,
                        "cssClass": "economy",
                    }
                },
                "indexerRows": {"visible": False},
                "frontVisible": True,
                "columnSpacers": [2],
                "disabledSeats": [
                    {"col": 0, "row": 0},
                    {"col": 1, "row": 0},
                    {"col": 2, "row": 0},
                    {"col": 3, "row": 0},
                    {"col": 0, "row": 1},
                    {"col": 1, "row": 1},
                    {"col": 2, "row": 1},
                    {"col": 3, "row": 1},
                    {"col": 0, "row": 2},
                    {"col": 1, "row": 2},
                    {"col": 2, "row": 2},
                    {"col": 3, "row": 2},
                    {"col": 2, "row": 3},
                    {"col": 3, "row": 3},
                    {"col": 2, "row": 4},
                    {"col": 2, "row": 5},
                    {"col": 2, "row": 6},
                    {"col": 0, "row": 7},
                    {"col": 1, "row": 7},
                    {"col": 2, "row": 7},
                    {"col": 3, "row": 7},
                    {"col": 0, "row": 8},
                    {"col": 1, "row": 8},
                    {"col": 2, "row": 8},
                    {"col": 3, "row": 8},
                    {"col": 0, "row": 9},
                    {"col": 1, "row": 9},
                    {"col": 2, "row": 9},
                    {"col": 3, "row": 9},
                    {"col": 0, "row": 10},
                    {"col": 1, "row": 10},
                    {"col": 2, "row": 10},
                    {"col": 3, "row": 10},
                    {"col": 2, "row": 8},
                    {"col": 2, "row": 9},
                    {"col": 2, "row": 10},
                    {"col": 2, "row": 11},
                ],
                "reservedSeats": [
                    {"col": 0, "row": 3},
                    {"col": 1, "row": 3},
                    {"col": 0, "row": 4},
                    {"col": 1, "row": 4},
                    {"col": 3, "row": 4},
                    {"col": 0, "row": 5},
                    {"col": 1, "row": 5},
                    {"col": 3, "row": 5},
                    {"col": 0, "row": 6},
                    {"col": 1, "row": 6},
                    {"col": 3, "row": 6},
                ],
                "selectedSeats": [],
                "indexerColumns": {"visible": False},
            },
            "cart": {"visible": True, "currency": "ARS ", "submitLabel": "Confirm"},
        },
    },
    "upper": {
        "enabledSeats": [37, 38, 41, 42],
        "labels": {
            "00": "1",
            "01": "2",
            "02": "3",
            "03": "4",
            "10": "5",
            "11": "6",
            "12": "7",
            "13": "8",
            "20": "9",
            "21": "10",
            "22": "11",
            "23": "12",
            "30": "13",
            "31": "14",
            "32": "15",
            "33": "16",
            "40": "17",
            "41": "18",
            "42": "19",
            "43": "20",
            "50": "21",
            "51": "22",
            "52": "23",
            "53": "24",
            "60": "25",
            "61": "26",
            "62": "27",
            "63": "28",
            "70": "29",
            "71": "30",
            "72": "31",
            "73": "32",
            "80": "33",
            "81": "34",
            "82": "35",
            "83": "36",
            "90": "37",
            "91": "38",
            "92": "39",
            "93": "40",
            "100": "41",
            "101": "42",
            "102": "43",
            "103": "44",
            "110": "45",
            "111": "46",
            "112": "47",
            "113": "48",
            "120": "49",
            "121": "50",
            "122": "51",
            "123": "52",
        },
        "options": {
            "map": {
                "rows": 13,
                "columns": 4,
                "seatTypes": {
                    "default": {
                        "label": "Economy",
                        "price": 20769,
                        "cssClass": "economy",
                    }
                },
                "indexerRows": {"visible": False},
                "frontVisible": True,
                "columnSpacers": [2],
                "disabledSeats": [
                    {"col": 2, "row": 2},
                    {"col": 3, "row": 2},
                    {"col": 2, "row": 3},
                    {"col": 3, "row": 3},
                ],
                "reservedSeats": [
                    {"col": 0, "row": 0},
                    {"col": 1, "row": 0},
                    {"col": 2, "row": 0},
                    {"col": 3, "row": 0},
                    {"col": 0, "row": 1},
                    {"col": 1, "row": 1},
                    {"col": 2, "row": 1},
                    {"col": 3, "row": 1},
                    {"col": 0, "row": 2},
                    {"col": 1, "row": 2},
                    {"col": 2, "row": 2},
                    {"col": 3, "row": 2},
                    {"col": 0, "row": 3},
                    {"col": 1, "row": 3},
                    {"col": 2, "row": 3},
                    {"col": 3, "row": 3},
                    {"col": 0, "row": 4},
                    {"col": 1, "row": 4},
                    {"col": 2, "row": 4},
                    {"col": 3, "row": 4},
                    {"col": 0, "row": 5},
                    {"col": 1, "row": 5},
                    {"col": 2, "row": 5},
                    {"col": 3, "row": 5},
                    {"col": 0, "row": 6},
                    {"col": 1, "row": 6},
                    {"col": 2, "row": 6},
                    {"col": 3, "row": 6},
                    {"col": 0, "row": 7},
                    {"col": 1, "row": 7},
                    {"col": 2, "row": 7},
                    {"col": 3, "row": 7},
                    {"col": 0, "row": 8},
                    {"col": 1, "row": 8},
                    {"col": 2, "row": 8},
                    {"col": 3, "row": 8},
                    {"col": 2, "row": 9},
                    {"col": 3, "row": 9},
                    {"col": 2, "row": 10},
                    {"col": 3, "row": 10},
                    {"col": 0, "row": 11},
                    {"col": 1, "row": 11},
                    {"col": 2, "row": 11},
                    {"col": 3, "row": 11},
                    {"col": 0, "row": 12},
                    {"col": 1, "row": 12},
                    {"col": 2, "row": 12},
                    {"col": 3, "row": 12},
                ],
                "selectedSeats": [],
                "indexerColumns": {"visible": False},
            },
            "cart": {"visible": True, "currency": "ARS ", "submitLabel": "Confirm"},
        },
    },
}

SEMICAMA = {
    "lower": {
        "enabledSeats": [],
        "labels": {
            "00": "?",
            "01": "?",
            "02": "?",
            "03": "?",
            "10": "?",
            "11": "?",
            "12": "?",
            "13": "?",
            "20": "?",
            "21": "?",
            "22": "?",
            "23": "?",
            "30": "60",
            "31": "61",
            "32": "?",
            "33": "?",
            "40": "62",
            "41": "63",
            "42": "?",
            "43": "73",
            "50": "64",
            "51": "65",
            "52": "?",
            "53": "75",
            "60": "66",
            "61": "67",
            "62": "?",
            "63": "77",
            "70": "?",
            "71": "?",
            "72": "?",
            "73": "?",
            "80": "?",
            "81": "?",
            "82": "?",
            "83": "?",
            "90": "?",
            "91": "?",
            "92": "?",
            "93": "?",
            "100": "?",
            "101": "?",
            "102": "?",
            "103": "?",
            "110": "?",
            "111": "?",
            "112": "?",
            "113": "?",
        },
        "options": {
            "map": {
                "rows": 11,
                "columns": 4,
                "seatTypes": {
                    "default": {
                        "label": "SemiCama",
                        "price": 29670,
                        "cssClass": "economy",
                    }
                },
                "indexerRows": {"visible": False},
                "frontVisible": True,
                "columnSpacers": [2],
                "disabledSeats": [
                    {"col": 0, "row": 0},
                    {"col": 1, "row": 0},
                    {"col": 2, "row": 0},
                    {"col": 3, "row": 0},
                    {"col": 0, "row": 1},
                    {"col": 1, "row": 1},
                    {"col": 2, "row": 1},
                    {"col": 3, "row": 1},
                    {"col": 0, "row": 2},
                    {"col": 1, "row": 2},
                    {"col": 2, "row": 2},
                    {"col": 3, "row": 2},
                    {"col": 2, "row": 3},
                    {"col": 3, "row": 3},
                    {"col": 2, "row": 4},
                    {"col": 2, "row": 5},
                    {"col": 2, "row": 6},
                    {"col": 0, "row": 7},
                    {"col": 1, "row": 7},
                    {"col": 2, "row": 7},
                    {"col": 3, "row": 7},
                    {"col": 0, "row": 8},
                    {"col": 1, "row": 8},
                    {"col": 2, "row": 8},
                    {"col": 3, "row": 8},
                    {"col": 0, "row": 9},
                    {"col": 1, "row": 9},
                    {"col": 2, "row": 9},
                    {"col": 3, "row": 9},
                    {"col": 0, "row": 10},
                    {"col": 1, "row": 10},
                    {"col": 2, "row": 10},
                    {"col": 3, "row": 10},
                    {"col": 2, "row": 8},
                    {"col": 2, "row": 9},
                    {"col": 2, "row": 10},
                    {"col": 2, "row": 11},
                ],
                "reservedSeats": [
                    {"col": 0, "row": 3},
                    {"col": 1, "row": 3},
                    {"col": 0, "row": 4},
                    {"col": 1, "row": 4},
                    {"col": 3, "row": 4},
                    {"col": 0, "row": 5},
                    {"col": 1, "row": 5},
                    {"col": 3, "row": 5},
                    {"col": 0, "row": 6},
                    {"col": 1, "row": 6},
                    {"col": 3, "row": 6},
                ],
                "selectedSeats": [],
                "indexerColumns": {"visible": False},
            },
            "cart": {"visible": True, "currency": "ARS ", "submitLabel": "Confirm"},
        },
    },
    "upper": {
        "enabledSeats": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            13,
            14,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            39,
            40,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
        ],
        "labels": {
            "00": "1",
            "01": "2",
            "02": "3",
            "03": "4",
            "10": "5",
            "11": "6",
            "12": "7",
            "13": "8",
            "20": "9",
            "21": "10",
            "22": "11",
            "23": "12",
            "30": "13",
            "31": "14",
            "32": "15",
            "33": "16",
            "40": "17",
            "41": "18",
            "42": "19",
            "43": "20",
            "50": "21",
            "51": "22",
            "52": "23",
            "53": "24",
            "60": "25",
            "61": "26",
            "62": "27",
            "63": "28",
            "70": "29",
            "71": "30",
            "72": "31",
            "73": "32",
            "80": "33",
            "81": "34",
            "82": "35",
            "83": "36",
            "90": "37",
            "91": "38",
            "92": "39",
            "93": "40",
            "100": "41",
            "101": "42",
            "102": "43",
            "103": "44",
            "110": "45",
            "111": "46",
            "112": "47",
            "113": "48",
            "120": "49",
            "121": "50",
            "122": "51",
            "123": "52",
        },
        "options": {
            "map": {
                "rows": 13,
                "columns": 4,
                "seatTypes": {
                    "default": {
                        "label": "SemiCama",
                        "price": 29670,
                        "cssClass": "economy",
                    }
                },
                "indexerRows": {"visible": False},
                "frontVisible": True,
                "columnSpacers": [2],
                "disabledSeats": [
                    {"col": 2, "row": 2},
                    {"col": 3, "row": 2},
                    {"col": 2, "row": 3},
                    {"col": 3, "row": 3},
                ],
                "reservedSeats": [
                    {"col": 0, "row": 9},
                    {"col": 1, "row": 9},
                    {"col": 0, "row": 10},
                    {"col": 1, "row": 10},
                ],
                "selectedSeats": [],
                "indexerColumns": {"visible": False},
            },
            "cart": {"visible": True, "currency": "ARS ", "submitLabel": "Confirm"},
        },
    },
}

CAMA_INDIVIDUAL = {
    "lower": {
        "enabledSeats": [60, 61, 62, 63, 64, 65, 66, 67, 73, 75, 77],
        "labels": {
            "00": "?",
            "01": "?",
            "02": "?",
            "03": "?",
            "10": "?",
            "11": "?",
            "12": "?",
            "13": "?",
            "20": "?",
            "21": "?",
            "22": "?",
            "23": "?",
            "30": "60",
            "31": "61",
            "32": "?",
            "33": "?",
            "40": "62",
            "41": "63",
            "42": "?",
            "43": "73",
            "50": "64",
            "51": "65",
            "52": "?",
            "53": "75",
            "60": "66",
            "61": "67",
            "62": "?",
            "63": "77",
            "70": "?",
            "71": "?",
            "72": "?",
            "73": "?",
            "80": "?",
            "81": "?",
            "82": "?",
            "83": "?",
            "90": "?",
            "91": "?",
            "92": "?",
            "93": "?",
            "100": "?",
            "101": "?",
            "102": "?",
            "103": "?",
            "110": "?",
            "111": "?",
            "112": "?",
            "113": "?",
        },
        "options": {
            "map": {
                "rows": 11,
                "columns": 4,
                "seatTypes": {
                    "default": {
                        "label": "SemiCama",
                        "price": 33010,
                        "cssClass": "economy",
                    }
                },
                "indexerRows": {"visible": False},
                "frontVisible": True,
                "columnSpacers": [2],
                "disabledSeats": [
                    {"col": 0, "row": 0},
                    {"col": 1, "row": 0},
                    {"col": 2, "row": 0},
                    {"col": 3, "row": 0},
                    {"col": 0, "row": 1},
                    {"col": 1, "row": 1},
                    {"col": 2, "row": 1},
                    {"col": 3, "row": 1},
                    {"col": 0, "row": 2},
                    {"col": 1, "row": 2},
                    {"col": 2, "row": 2},
                    {"col": 3, "row": 2},
                    {"col": 2, "row": 3},
                    {"col": 3, "row": 3},
                    {"col": 2, "row": 4},
                    {"col": 2, "row": 5},
                    {"col": 2, "row": 6},
                    {"col": 0, "row": 7},
                    {"col": 1, "row": 7},
                    {"col": 2, "row": 7},
                    {"col": 3, "row": 7},
                    {"col": 0, "row": 8},
                    {"col": 1, "row": 8},
                    {"col": 2, "row": 8},
                    {"col": 3, "row": 8},
                    {"col": 0, "row": 9},
                    {"col": 1, "row": 9},
                    {"col": 2, "row": 9},
                    {"col": 3, "row": 9},
                    {"col": 0, "row": 10},
                    {"col": 1, "row": 10},
                    {"col": 2, "row": 10},
                    {"col": 3, "row": 10},
                    {"col": 2, "row": 8},
                    {"col": 2, "row": 9},
                    {"col": 2, "row": 10},
                    {"col": 2, "row": 11},
                ],
                "reservedSeats": [],
                "selectedSeats": [],
                "indexerColumns": {"visible": False},
            },
            "cart": {"visible": True, "currency": "ARS ", "submitLabel": "Confirm"},
        },
    },
    "upper": {
        "enabledSeats": [],
        "labels": {
            "00": "1",
            "01": "2",
            "02": "3",
            "03": "4",
            "10": "5",
            "11": "6",
            "12": "7",
            "13": "8",
            "20": "9",
            "21": "10",
            "22": "11",
            "23": "12",
            "30": "13",
            "31": "14",
            "32": "15",
            "33": "16",
            "40": "17",
            "41": "18",
            "42": "19",
            "43": "20",
            "50": "21",
            "51": "22",
            "52": "23",
            "53": "24",
            "60": "25",
            "61": "26",
            "62": "27",
            "63": "28",
            "70": "29",
            "71": "30",
            "72": "31",
            "73": "32",
            "80": "33",
            "81": "34",
            "82": "35",
            "83": "36",
            "90": "37",
            "91": "38",
            "92": "39",
            "93": "40",
            "100": "41",
            "101": "42",
            "102": "43",
            "103": "44",
            "110": "45",
            "111": "46",
            "112": "47",
            "113": "48",
            "120": "49",
            "121": "50",
            "122": "51",
            "123": "52",
        },
        "options": {
            "map": {
                "rows": 13,
                "columns": 4,
                "seatTypes": {
                    "default": {
                        "label": "Economy",
                        "price": 33010,
                        "cssClass": "economy",
                    }
                },
                "indexerRows": {"visible": False},
                "frontVisible": True,
                "columnSpacers": [2],
                "disabledSeats": [
                    {"col": 2, "row": 2},
                    {"col": 3, "row": 2},
                    {"col": 2, "row": 3},
                    {"col": 3, "row": 3},
                ],
                "reservedSeats": [
                    {"col": 0, "row": 0},
                    {"col": 1, "row": 0},
                    {"col": 2, "row": 0},
                    {"col": 3, "row": 0},
                    {"col": 0, "row": 1},
                    {"col": 1, "row": 1},
                    {"col": 2, "row": 1},
                    {"col": 3, "row": 1},
                    {"col": 0, "row": 2},
                    {"col": 1, "row": 2},
                    {"col": 2, "row": 2},
                    {"col": 3, "row": 2},
                    {"col": 0, "row": 3},
                    {"col": 1, "row": 3},
                    {"col": 2, "row": 3},
                    {"col": 3, "row": 3},
                    {"col": 0, "row": 4},
                    {"col": 1, "row": 4},
                    {"col": 2, "row": 4},
                    {"col": 3, "row": 4},
                    {"col": 0, "row": 5},
                    {"col": 1, "row": 5},
                    {"col": 2, "row": 5},
                    {"col": 3, "row": 5},
                    {"col": 0, "row": 6},
                    {"col": 1, "row": 6},
                    {"col": 2, "row": 6},
                    {"col": 3, "row": 6},
                    {"col": 0, "row": 7},
                    {"col": 1, "row": 7},
                    {"col": 2, "row": 7},
                    {"col": 3, "row": 7},
                    {"col": 0, "row": 8},
                    {"col": 1, "row": 8},
                    {"col": 2, "row": 8},
                    {"col": 3, "row": 8},
                    {"col": 0, "row": 9},
                    {"col": 1, "row": 9},
                    {"col": 2, "row": 9},
                    {"col": 3, "row": 9},
                    {"col": 0, "row": 10},
                    {"col": 1, "row": 10},
                    {"col": 2, "row": 10},
                    {"col": 3, "row": 10},
                    {"col": 0, "row": 11},
                    {"col": 1, "row": 11},
                    {"col": 2, "row": 11},
                    {"col": 3, "row": 11},
                    {"col": 0, "row": 12},
                    {"col": 1, "row": 12},
                    {"col": 2, "row": 12},
                    {"col": 3, "row": 12},
                ],
                "selectedSeats": [],
                "indexerColumns": {"visible": False},
            },
            "cart": {"visible": True, "currency": "ARS ", "submitLabel": "Confirm"},
        },
    },
}

SINGLE_FLOOR_SEATER = {
    "lower": {
        "enabledSeats": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "labels": {
            "00": "D",
            "01": "D",
            "02": "?",
            "03": "?",
            "10": "D",
            "11": "D",
            "12": "1",
            "13": "2",
            "20": "3",
            "21": "4",
            "22": "5",
            "23": "6",
            "30": "7",
            "31": "8",
            "32": "9",
            "33": "10",
            "40": "11",
            "41": "12",
            "42": "13",
            "43": "14",
            "50": "15",
            "51": "16",
            "52": "17",
            "53": "18",
            "60": "19",
            "61": "20",
            "62": "21",
            "63": "22",
            "70": "23",
            "71": "24",
            "72": "25",
            "73": "26",
            "80": "27",
            "81": "28",
            "82": "29",
            "83": "30",
            "90": "31",
            "91": "32",
            "92": "33",
            "93": "34",
            "100": "35",
            "101": "36",
            "102": "37",
            "103": "38",
            "110": "39",
            "111": "40",
            "112": "41",
            "113": "42",
        },
        "options": {
            "map": {
                "rows": 11,
                "columns": 4,
                "seatTypes": {
                    "default": {
                        "label": "Seater",
                        "price": 100,
                        "cssClass": "first-class",
                    }
                },
                "indexerRows": {"visible": False},
                "frontVisible": True,
                "columnSpacers": [2],
                "disabledSeats": [{"col": 2, "row": 0}, {"col": 3, "row": 0}],
                "reservedSeats": [
                    {"row": 0, "col": 0},
                    {"row": 0, "col": 1},
                    {"row": 1, "col": 0},
                    {"row": 1, "col": 1},
                ],
                "selectedSeats": [],
                "indexerColumns": {"visible": False},
            },
            "cart": {"visible": True, "currency": "ARS ", "submitLabel": "Confirm"},
        },
    },
}

SEAT_CHART_DICTS = [SEMICAMA_PROMO, SEMICAMA, CAMA_INDIVIDUAL, SINGLE_FLOOR_SEATER]
