COMPANIES = [
    "KMB",
    "El Cometa",
    "Tolkeyen Patagonia",
    "Nordic Travel",
    "Autotransporte 21",
    "Autobuses Quirquincho",
    "R\u00e1pido Internacional",
    "Empresa Silvia",
    "Albizzatti",
    "Transportes Rinc\u00f3n",
    "Aerobols\u00f3n",
    "Alto Limay",
    "Expreso Singer",
    "JBL",
    "Expreso del Oeste",
    "Buses Potos\u00ed",
    "La Encarnacena",
    "Rio Uruguay",
    "La Uni\u00f3n",
    "V\u00eda Tac",
    "Central Argentino",
    "Lazo",
    "Socsa",
    "El Alba del Sur",
    "Eticket",
    "Sarmiento",
    "V\u00eda Bariloche",
    "Expreso Alberino",
    "Aguila Dorada Bis",
    "Taqsa",
    "Evelia",
    "C\u00f3ndor Estrella",
    "Rutamar",
    "Dumascat",
    "Aeroangostura",
    "Sierras Sur",
    "Balut",
    "Empresa Tas",
    "Aymar\u00e1 Turismo",
    "Macor",
    "Nuestra Se\u00f1ora de la Asunci\u00f3n - Argentina",
    "Chalt\u00e9n Travel",
    "Valle del Sol",
    "Colonia Express",
    "Rio Uruguay de Kruk Lila Maria",
    "El \u00c1guila",
    "Guaire\u00f1a",
    "Fredes Turismo",
    "San Juan Mar del Plata",
    "Crucero del Norte",
    "20 de Junio",
    "Platabus",
    "Empresa Vallecito",
    "\u00d1and\u00fa del Sur",
    "Sol Bus",
    "Reta Tur",
    "Micromar",
    "Puma Bus",
    "Ray Bus",
    "Horianski",
    "El Practico",
    "La Diligencia",
    "Transfer Line",
    "El Rosarino",
    "Rutatlantica",
    "Diferencial Transierras",
    "Buses Lep",
    "Transporte Serrano",
    "Union Platense",
    "El Triunfo",
    "Leader",
    "Nossar",
    "El Tat\u00fa Carretero",
    "Cal Tur",
    "El Turista",
    "Gray Line",
    "Tony Tur",
    "JoviBus",
    "Petrobus",
    "Cooperativa Sportman",
    "La Trochita",
    "El Pulqui",
    "ETAP",
    "Expreso R\u00edo Paran\u00e1",
    "Del Sur y Media Agua",
    "Empresa General Artigas",
    "La Yute\u00f1a",
    "Ersa",
    "La Paraguaya Internacional",
    "Gustavo Chavez Turismo",
    "Masterbus",
    "Bus Vitivin\u00edcola",
    "Transportes Automotores 20 de Junio S.A.",
    "Puerto Tirol",
    "Itati",
    "Crucero del Sur",
    "Cata Internacional",
    "El Valle",
    "Iselin",
    "25 de Agosto",
    "Transporte Las Grutas",
    "Tramat",
    "Ceferino",
    "Andesmar",
    "Sierras Cordobesas",
    "Expreso Paraguay",
    "Turismo Uspallata",
    "Royal Class",
    "Tren Patagonico",
    "Microsur",
    "Marga",
    "Fono Bus",
    "Transaustral",
    "Buttini",
    "Tienda Le\u00f3n",
    "Expreso Sauce",
    "Plusmar",
    "Expreso La Plata",
    "Capital del Monte",
    "Expreso Hernandarias",
    "R\u00e1pido Bus",
    "Eder",
    "La Santaniana",
    "Potos\u00ed Buses",
    "Tata R\u00e1pido",
    "Vosa",
    "Sierras de Calamuchita",
    "Betel Ejecutivo",
    "Transporte San Jose",
    "El Cometa Bis",
    "Intercordoba",
    "La Serranita",
    "Expreso Transamericano",
    "Rio Uruguay de Flecha de Oro",
]

SEAT_CHARTS = [
    "Cama",
    "Cama Executivo",
    "Cama Individual",
    "Cama Suite",
    "Semi Cama",
    "Semi Cama Promocional",
    "Semi Cama Promocional No Reembolsable",
]
