# Generated by Django 4.1.5 on 2023-01-20 22:58

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=300)),
                ("description", models.CharField(blank=True, max_length=800)),
                ("website", models.URLField(blank=True)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        upload_to=companies.models.company_cover_path,
                        verbose_name="Cover photo",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to=companies.models.company_thumbnail_path,
                        verbose_name="Thumbnail photo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
    ]
