# Generated by Django 4.1.5 on 2023-01-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "company",
                "verbose_name_plural": "companies",
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
