# Generated by Django 4.2.2 on 2023-07-10 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("json", models.JSONField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seatcharts",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
    ]
