# Generated by Django 4.2.2 on 2023-11-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_seatchart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(max_length=200, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.CharField(
                blank=True, max_length=800, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="phone"),
        ),
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(max_length=300, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, verbose_name="website"),
        ),
        migrations.AlterField(
            model_name="seatchart",
            name="json",
            field=models.JSONField(verbose_name="json"),
        ),
        migrations.AlterField(
            model_name="seatchart",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
    ]
