# Generated by Django 4.2.2 on 2023-07-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_seatchart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seatchart",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
