# Generated by Django 5.0.3 on 2024-07-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_alter_seatchart_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="name"),
        ),
    ]
