# Generated by Django 5.0.3 on 2024-08-13 17:48

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_alter_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seatchart",
            name="json",
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="json",
            ),
        ),
    ]
