# Generated by Django 5.0.3 on 2024-10-09 17:43

import django.core.serializers.json
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="settings",
            options={
                "ordering": ["name"],
                "verbose_name": "settings",
                "verbose_name_plural": "settings",
            },
        ),
        migrations.AddField(
            model_name="settings",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="json_val",
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
