# Generated by Django 5.0.3 on 2024-10-09 17:45

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_settings_options_settings_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="json_val",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
