# Generated by Django 4.1.5 on 2023-02-06 17:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_alter_company_options_alter_company_slug"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "abbr",
                    models.CharField(
                        blank=True,
                        help_text="Used internally as a reference",
                        max_length=7,
                        verbose_name="Abbreviation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ]
                    ),
                ),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("C", "Cama"),
                            ("S", "Semicama"),
                            ("E", "Executive"),
                            ("O", "Other"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
                (
                    "seat_status",
                    models.CharField(
                        choices=[
                            ("A", "Available"),
                            ("B", "Booked"),
                            ("R", "Reserved"),
                            ("H", "Onhold"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="orders.passenger",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "departure",
                    models.DateTimeField(verbose_name="Departure Date & Time"),
                ),
                ("arrival", models.DateTimeField(verbose_name="Arrival Date & Time")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("C", "Cancelled"),
                            ("H", "OnHold"),
                            ("D", "Delayed"),
                            ("O", "Other"),
                        ],
                        default="A",
                        max_length=2,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("D", "Direct"), ("I", "Indirect"), ("O", "Other")],
                        default="D",
                        max_length=2,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="trips/%Y/%m/%d")),
                ("description", models.TextField(blank=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="companies.company",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips_inbound",
                        to="trips.location",
                    ),
                ),
                (
                    "orders",
                    models.ManyToManyField(
                        related_name="trips",
                        through="orders.OrderItem",
                        to="orders.order",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips_outbound",
                        to="trips.location",
                    ),
                ),
                (
                    "passengers",
                    models.ManyToManyField(
                        related_name="trips",
                        through="trips.Seat",
                        to="orders.passenger",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="seat",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="trips.trip",
            ),
        ),
    ]
