# Generated by Django 4.1.5 on 2023-01-23 00:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_alter_company_options_alter_company_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "abbr",
                    models.CharField(
                        blank=True,
                        help_text="Used internally as a reference",
                        max_length=7,
                        verbose_name="Abbreviation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "departure",
                    models.DateTimeField(verbose_name="Departure Date & Time"),
                ),
                ("arrival", models.DateTimeField(verbose_name="Arrival Date & Time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("C", "Cancelled"),
                            ("H", "OnHold"),
                            ("D", "Delayed"),
                            ("O", "Other"),
                        ],
                        default="A",
                        max_length=2,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("D", "Direct"), ("I", "Indirect"), ("O", "Other")],
                        default="D",
                        max_length=2,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="trips/%Y/%m/%d")),
                ("description", models.TextField(blank=True)),
                (
                    "seats_available",
                    models.PositiveSmallIntegerField(
                        default=45,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="companies.company",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips_inbound",
                        to="trips.location",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips_outbound",
                        to="trips.location",
                    ),
                ),
            ],
        ),
    ]
