# Generated by Django 4.1.5 on 2023-01-29 18:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="price",
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ]
                    ),
                ),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("C", "Cama"),
                            ("S", "Semicama"),
                            ("E", "Executive"),
                            ("O", "Other"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
                (
                    "seat_status",
                    models.CharField(
                        choices=[
                            ("A", "Available"),
                            ("B", "Booked"),
                            ("R", "Reserved"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
    ]
