# Generated by Django 4.1.7 on 2023-04-02 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_trip_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trip",
            options={"ordering": ["departure"]},
        ),
    ]
