# Generated by Django 4.1.5 on 2023-01-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_remove_trip_price_seat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="seats_available",
        ),
    ]
