# Generated by Django 4.1.5 on 2023-01-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_remove_trip_seats_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="available",
        ),
    ]
