# Generated by Django 4.1.5 on 2023-02-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_remove_trip_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="price",
        ),
        migrations.AddField(
            model_name="trip",
            name="price",
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
            preserve_default=False,
        ),
    ]
