# Generated by Django 4.2.2 on 2023-11-23 14:47

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_alter_seat_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["name"],
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="address_line1",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Address line 1"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="address_line2",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Address line 2"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.CharField(blank=True, max_length=64, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="location",
            name="country",
            field=django_countries.fields.CountryField(default="AR", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, null=True, verbose_name="Latitude"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, null=True, verbose_name="Longitude"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Postal Code"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="state",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="State/Province"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="abbr",
            field=models.CharField(
                blank=True,
                help_text="Used internally as a reference",
                max_length=7,
                verbose_name="abbreviation",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="location",
            name="slug",
            field=models.SlugField(max_length=200, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="seat",
            name="seat_number",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="seat number",
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="seat_status",
            field=models.CharField(
                choices=[
                    ("A", "Available"),
                    ("B", "Booked"),
                    ("R", "Reserved"),
                    ("H", "Onhold"),
                ],
                default="A",
                max_length=1,
                verbose_name="seat status",
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="seat_type",
            field=models.CharField(
                choices=[
                    ("C", "Cama"),
                    ("S", "Semicama"),
                    ("E", "Executive"),
                    ("O", "Other"),
                ],
                default="C",
                max_length=1,
                verbose_name="seat type",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="trips/%Y/%m/%d", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="mode",
            field=models.CharField(
                choices=[("D", "Direct"), ("I", "Indirect"), ("O", "Other")],
                default="D",
                max_length=2,
                verbose_name="mode",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="slug",
            field=models.SlugField(max_length=200, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Active"),
                    ("C", "Cancelled"),
                    ("H", "OnHold"),
                    ("D", "Delayed"),
                    ("O", "Other"),
                ],
                default="A",
                max_length=2,
                verbose_name="status",
            ),
        ),
    ]
