# Generated by Django 4.2.2 on 2023-11-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_alter_location_options_location_address_line1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips_inbound",
                to="trips.location",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips_outbound",
                to="trips.location",
            ),
        ),
    ]
