# Generated by Django 5.0.3 on 2024-05-29 16:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_alter_company_address_alter_company_description_and_more"),
        ("trips", "0006_alter_trip_destination_alter_trip_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("slug", models.SlugField(max_length=200, verbose_name="slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="routes/%Y/%m/%d", verbose_name="image"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Duration in Hours",
                    ),
                ),
                ("price", models.JSONField(default=dict, verbose_name="price")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="companies.company",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes_inbound",
                        to="trips.location",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes_outbound",
                        to="trips.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
            },
        ),
    ]
