# Generated by Django 5.0.3 on 2024-05-29 23:10

import django.db.models.deletion
import trips.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0007_route"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival", models.TimeField(verbose_name="arrival")),
                ("departure", models.TimeField(verbose_name="departure")),
                ("order", trips.fields.OrderField(blank=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_stops",
                        to="trips.location",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trips.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "stop",
                "verbose_name_plural": "stops",
                "ordering": ("order",),
            },
        ),
    ]
