# Generated by Django 5.0.3 on 2024-05-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_stop"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="category",
            field=models.CharField(
                choices=[
                    ("C", "Cama"),
                    ("S", "Semicama"),
                    ("E", "Executive"),
                    ("O", "Other"),
                ],
                default="S",
                max_length=2,
                verbose_name="category",
            ),
        ),
    ]
