# Generated by Django 5.0.3 on 2024-06-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0010_alter_route_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["name"],
                "verbose_name": "location",
                "verbose_name_plural": "locations",
            },
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"verbose_name": "route", "verbose_name_plural": "routes"},
        ),
        migrations.AlterModelOptions(
            name="seat",
            options={"verbose_name": "seat", "verbose_name_plural": "seats"},
        ),
        migrations.AlterModelOptions(
            name="trip",
            options={
                "ordering": ["departure"],
                "verbose_name": "trip",
                "verbose_name_plural": "trips",
            },
        ),
    ]
