# Generated by Django 5.0.3 on 2024-06-27 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0011_alter_location_options_alter_route_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to="trips.route",
            ),
        ),
    ]
