# Generated by Django 5.0.3 on 2024-07-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0012_trip_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="schedule",
            field=models.JSONField(default=dict, verbose_name="schedule"),
        ),
    ]
