# Generated by Django 5.0.3 on 2024-07-06 15:51

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0013_trip_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="schedule",
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="schedule",
            ),
        ),
    ]
