# Generated by Django 5.0.3 on 2024-07-06 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0015_remove_stop_arrival_remove_stop_departure"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="arrival",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2000, 1, 1, 11, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="arrival",
            ),
        ),
        migrations.AddField(
            model_name="stop",
            name="departure",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2000, 1, 1, 11, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="departure",
            ),
        ),
    ]
