# Generated by Django 5.0.3 on 2024-07-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0017_alter_location_abbr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="price",
        ),
    ]
