# Generated by Django 5.0.3 on 2024-07-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0020_alter_price_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="price",
            unique_together={("route", "origin", "destination", "category")},
        ),
    ]
