# Generated by Django 5.0.3 on 2024-07-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0021_alter_price_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="category",
        ),
    ]
