# Generated by Django 5.0.3 on 2024-07-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0022_remove_route_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="category",
            field=models.CharField(
                choices=[
                    ("C", "Cama"),
                    ("S", "Semicama"),
                    ("E", "Executive"),
                    ("O", "Other"),
                ],
                default="S",
                max_length=2,
                verbose_name="category",
            ),
        ),
    ]
