# Generated by Django 5.0.3 on 2024-09-30 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_passenger_gender"),
        ("trips", "0025_alter_seat_passenger"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="order_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booked_seats",
                to="orders.orderitem",
            ),
        ),
    ]
