# Generated by Django 5.1.4 on 2025-01-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0026_seat_order_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="State/Province"
            ),
        ),
    ]
