# Generated by Django 5.1.4 on 2025-01-25 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0027_alter_location_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="route_stops",
                to="trips.location",
            ),
        ),
    ]
