# Generated by Django 4.1.5 on 2023-01-28 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passenger",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AddField(
            model_name="passenger",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="passenger",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="passenger",
            index=models.Index(
                fields=["-created_on"], name="orders_pass_created_b7ac92_idx"
            ),
        ),
    ]
