# Generated by Django 4.1.5 on 2023-02-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="seats",
            field=models.CharField(default="1, 2, 3", max_length=20),
            preserve_default=False,
        ),
    ]
