# Generated by Django 4.1.5 on 2023-02-01 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_passenger_options_passenger_created_on_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passenger",
            name="order_item",
        ),
        migrations.AddField(
            model_name="passenger",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passengers",
                to="orders.order",
            ),
            preserve_default=False,
        ),
    ]
