# Generated by Django 4.1.5 on 2023-02-13 20:13

from django.db import migrations, models
import orders.validators


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="birth_date",
            field=models.DateField(validators=[orders.validators.validate_birth_date]),
        ),
    ]
