# Generated by Django 4.1.5 on 2023-02-09 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_seats"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="passenger",
            constraint=models.CheckConstraint(
                check=models.Q(("birth_date__lt", datetime.date(2023, 2, 9))),
                name="birth_date_not_in_future",
            ),
        ),
    ]
