# Generated by Django 4.1.5 on 2023-02-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_passenger_trip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                help_text="We'll email the ticket to this email id.", max_length=254
            ),
        ),
    ]
