# Generated by Django 4.2.2 on 2023-11-23 14:47

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import orders.validators


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_coupon_order_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                help_text="We'll email the ticket to this email id.",
                max_length=254,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="order",
            name="residence",
            field=django_countries.fields.CountryField(
                help_text="This helps us to show you the best payment options.",
                max_length=2,
                verbose_name="residence",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="birth_date",
            field=models.DateField(
                validators=[orders.validators.validate_birth_date],
                verbose_name="birth date",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="document_number",
            field=models.CharField(max_length=50, verbose_name="document number"),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="document_type",
            field=models.CharField(
                choices=[
                    (None, "Identification"),
                    ("DNI", "DNI"),
                    ("PASSPORT", "PASSPORT"),
                    ("CE", "CEDULA"),
                    ("LE", "LE"),
                    ("LC", "LC"),
                    ("CUIT", "CUIT"),
                    ("NIE", "NIE"),
                    ("RG", "RG"),
                    ("RNE", "RNE"),
                    ("CPF", "CPF"),
                    ("RUT", "RUT"),
                    ("CURP", "CURP"),
                    ("CNPJ", "CNPJ"),
                ],
                max_length=10,
                verbose_name="document type",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="gender",
            field=models.CharField(
                choices=[(None, "Gender"), ("F", "Female"), ("M", "Male")],
                max_length=1,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="nationality",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="nationality"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="phone_number",
            field=models.CharField(
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
