# Generated by Django 5.0.3 on 2024-06-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_email_alter_order_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_on"],
                "verbose_name": "order",
                "verbose_name_plural": "orders",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
            },
        ),
        migrations.AlterModelOptions(
            name="passenger",
            options={
                "ordering": ["-created_on"],
                "verbose_name": "passenger",
                "verbose_name_plural": "passengers",
            },
        ),
    ]
