# Generated by Django 5.0.3 on 2024-08-02 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_orderitem_trip"),
        ("trips", "0024_remove_trip_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="trips.location",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="trips.location",
            ),
        ),
    ]
