# Generated by Django 5.0.3 on 2024-08-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_orderitem_destination_orderitem_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="gender",
            field=models.CharField(
                choices=[
                    (None, "Gender"),
                    ("F", "Female"),
                    ("M", "Male"),
                    ("O", "Other"),
                ],
                max_length=1,
                verbose_name="gender",
            ),
        ),
    ]
