# Generated by Django 5.0.3 on 2024-10-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_passenger_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="document_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="document number"
            ),
        ),
    ]
