name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  MP_PUBLIC_KEY: ${{ secrets.MP_PUBLIC_KEY }}
  MP_ACCESS_TOKEN: ${{ secrets.MP_ACCESS_TOKEN }}
  MP_CLIENT_ID: ${{ secrets.MP_CLIENT_ID }}
  MP_CLIENT_SECRET: ${{ secrets.MP_CLIENT_SECRET }}
  STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_WEBHOOK_SIGNING_SECRET: ${{ secrets.STRIPE_WEBHOOK_SIGNING_SECRET }}

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        poetry-version: ["1.7.1"]
        database: [postgres]
        os: [ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Add environment variables to .env
        run: |
          echo DEBUG=1 >> .env
          echo DJANGO_ALLOWED_HOSTS=* >> .env
          echo DATABASE_NAME=falcon >> .env
          echo DATABASE_USER=postgres >> .env
          echo DATABASE_PASSWORD=postgres >> .env
          echo DATABASE_HOST=localhost >> .env
          echo SECRET_KEY=sEcReTKeYtORuNTeSts >> .env

      - name: Setup postgres database
        uses: harmon758/postgresql-action@v1
        if: matrix.database == 'postgres'
        with:
          postgresql version: "14.6"
          postgresql db: "falcon"
          postgresql user: "postgres"
          postgresql password: "postgres"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry ${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
          
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run coverage run --source='.' manage.py test -v 2

        # run the next steps even if some tests fails see `if: always()`

      - name: Generate xml report
        run: poetry run coverage xml
        if: always()

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: Falcon coverage
          verbose: true
